Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df["Financing"] = [60, 50, 70] # add one column of data in which the values equal to a list
df
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[60], line 1[0m
[0;32m----> 1[0m df[[38;5;124m"[39m[38;5;124mFinancing[39m[38;5;124m"[39m] [38;5;241m=[39m [[38;5;241m60[39m, [38;5;241m50[39m, [38;5;241m70[39m] [38;5;66;03m# add one column of data in which the values equal to a list[39;00m
[1;32m      2[0m df

File [0;32m/opt/anaconda3/lib/python3.12/site-packages/pandas/core/frame.py:4311[0m, in [0;36mDataFrame.__setitem__[0;34m(self, key, value)[0m
[1;32m   4308[0m     [38;5;28mself[39m[38;5;241m.[39m_setitem_array([key], value)
[1;32m   4309[0m [38;5;28;01melse[39;00m:
[1;32m   4310[0m     [38;5;66;03m# set column[39;00m
[0;32m-> 4311[0m     [38;5;28mself[39m[38;5;241m.[39m_set_item(key, value)

File [0;32m/opt/anaconda3/lib/python3.12/site-packages/pandas/core/frame.py:4524[0m, in [0;36mDataFrame._set_item[0;34m(self, key, value)[0m
[1;32m   4514[0m [38;5;28;01mdef[39;00m [38;5;21m_set_item[39m([38;5;28mself[39m, key, value) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[1;32m   4515[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m   4516[0m [38;5;124;03m    Add series to DataFrame in specified column.[39;00m
[1;32m   4517[0m 
[0;32m   (...)[0m
[1;32m   4522[0m [38;5;124;03m    ensure homogeneity.[39;00m
[1;32m   4523[0m [38;5;124;03m    """[39;00m
[0;32m-> 4524[0m     value, refs [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_sanitize_column(value)
[1;32m   4526[0m     [38;5;28;01mif[39;00m (
[1;32m   4527[0m         key [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mcolumns
[1;32m   4528[0m         [38;5;129;01mand[39;00m value[38;5;241m.[39mndim [38;5;241m==[39m [38;5;241m1[39m
[1;32m   4529[0m         [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(value[38;5;241m.[39mdtype, ExtensionDtype)
[1;32m   4530[0m     ):
[1;32m   4531[0m         [38;5;66;03m# broadcast across multiple columns if necessary[39;00m
[1;32m   4532[0m         [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39mcolumns[38;5;241m.[39mis_unique [38;5;129;01mor[39;00m [38;5;28misinstance[39m([38;5;28mself[39m[38;5;241m.[39mcolumns, MultiIndex):

File [0;32m/opt/anaconda3/lib/python3.12/site-packages/pandas/core/frame.py:5266[0m, in [0;36mDataFrame._sanitize_column[0;34m(self, value)[0m
[1;32m   5263[0m     [38;5;28;01mreturn[39;00m _reindex_for_setitem(value, [38;5;28mself[39m[38;5;241m.[39mindex)
[1;32m   5265[0m [38;5;28;01mif[39;00m is_list_like(value):
[0;32m-> 5266[0m     com[38;5;241m.[39mrequire_length_match(value, [38;5;28mself[39m[38;5;241m.[39mindex)
[1;32m   5267[0m arr [38;5;241m=[39m sanitize_array(value, [38;5;28mself[39m[38;5;241m.[39mindex, copy[38;5;241m=[39m[38;5;28;01mTrue[39;00m, allow_2d[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m   5268[0m [38;5;28;01mif[39;00m (
[1;32m   5269[0m     [38;5;28misinstance[39m(value, Index)
[1;32m   5270[0m     [38;5;129;01mand[39;00m value[38;5;241m.[39mdtype [38;5;241m==[39m [38;5;124m"[39m[38;5;124mobject[39m[38;5;124m"[39m
[0;32m   (...)[0m
[1;32m   5273[0m     [38;5;66;03m# TODO: Remove kludge in sanitize_array for string mode when enforcing[39;00m
[1;32m   5274[0m     [38;5;66;03m# this deprecation[39;00m

File [0;32m/opt/anaconda3/lib/python3.12/site-packages/pandas/core/common.py:573[0m, in [0;36mrequire_length_match[0;34m(data, index)[0m
[1;32m    569[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    570[0m [38;5;124;03mCheck the length of data matches the length of the index.[39;00m
[1;32m    571[0m [38;5;124;03m"""[39;00m
[1;32m    572[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(data) [38;5;241m!=[39m [38;5;28mlen[39m(index):
[0;32m--> 573[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    574[0m         [38;5;124m"[39m[38;5;124mLength of values [39m[38;5;124m"[39m
[1;32m    575[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124m([39m[38;5;132;01m{[39;00m[38;5;28mlen[39m(data)[38;5;132;01m}[39;00m[38;5;124m) [39m[38;5;124m"[39m
[1;32m    576[0m         [38;5;124m"[39m[38;5;124mdoes not match length of index [39m[38;5;124m"[39m
[1;32m    577[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124m([39m[38;5;132;01m{[39;00m[38;5;28mlen[39m(index)[38;5;132;01m}[39;00m[38;5;124m)[39m[38;5;124m"[39m
[1;32m    578[0m     )

[0;31mValueError[0m: Length of values (3) does not match length of index (4)

